#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

#pragma kernel CSMain

Texture2D<float4> _PreviousBuffer;
RWTexture2D<float4> _CurrentBuffer;

float _Width;
float _Height;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 seedUV = _PreviousBuffer[id.xy].xy;
    float2 currentUV = float2(id.xy) / float2(_Width, _Height);

    _CurrentBuffer[id.xy] = float4(distance(seedUV, currentUV) * float3(1.0, 1.0, 1.0), 1.0);
}